name: linq
description: LinQ
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^2.12.0-0

dependencies:
  flutter:
    sdk: flutter
  sqlite:
    git: https://github.com/lamtx/sqlite.git
  #    path: ../sqlite
  ext:
    git: https://github.com/lamtx/ext.git
#    path: ../ext

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: