name: linq
description: LinQ
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  ext:
    git: https://github.com/lamtx/ext.git
  meta: any
  sqlite:
    git: https://github.com/lamtx/sqlite.git
