name: linq
description: LinQ
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.18.0
  ext:
    git: https://github.com/lamtx/ext.git
  meta: any
  sqlite:
    git: https://github.com/lamtx/sqlite.git
